Repository cyberway/cyberway, pull requests merged in 2019-03, with the labels that each got.

#313 Add limits on editing tables in other contracts. #258
  libraries/chain/wasm_chaindb_interface.ipp
Labels: High

#331 Several fixes for replaying chain. #330
  libraries/chain/chaindb/abi_info.cpp
  libraries/chain/chaindb/cache_map.cpp
  libraries/chain/chaindb/controller.cpp
  libraries/chain/chaindb/undo_state.cpp
  libraries/chain/include/cyberway/chaindb/cache_map.hpp
  libraries/chain/include/cyberway/chaindb/controller.hpp
Labels: bug

#336 Fix resync with block producer node. #330
  libraries/chain/block_log.cpp
  libraries/chain/chaindb/journal.cpp
  libraries/chain/chaindb/mongo_driver.cpp
  libraries/chain/chaindb/undo_state.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/cyberway/chaindb/common.hpp
  libraries/chain/include/cyberway/chaindb/journal.hpp
Labels: bug

#412 Fix importing delegation objects to genesis #411
  libraries/chain/genesis/genesis_read.cpp
Labels: bug

#413 Missing names object in importing genesis delegation #411
  libraries/chain/genesis/genesis_read.cpp
Labels: bug

#418 Add missing index in golos.vesting table when genesis read #417
  libraries/chain/genesis/genesis_accounts.cpp
Labels: bug

#436 Fix problem with scheduling when BP reconnect to chain #430
  libraries/chain/include/eosio/chain/block_header_state.hpp
Labels: Medium, bug

#439 Fix parsing of mongodb names #437
  libraries/chain/chaindb/mongo_driver.cpp
  libraries/chain/chaindb/names.cpp
  libraries/chain/include/cyberway/chaindb/names.hpp
Labels: bug
