Repository cyberway/cyberway, pull requests merged in 2019-06, with the labels that each got.

#797 Genesis: fill total_votes of stake stat object #789
  programs/create-genesis/genesis_create.cpp
Labels: bug

#786 Add number to event-engine messages #785
  plugins/event_engine_plugin/event_engine_plugin.cpp
  plugins/event_engine_plugin/include/eosio/event_engine_plugin/messages.hpp
Labels: High

#809 Fix behaviour with removed operation dump files #807
  programs/create-genesis/ee_genesis/genesis_ee_builder.cpp
  programs/create-genesis/ee_genesis/genesis_ee_builder.hpp
Labels: Medium, bug

#815 Fix segfault. #813
  libraries/chain/chaindb/mongo_driver.cpp
Labels: bug

#814 Fix cleos setabi: base64 decode abi obtained from api #811
  programs/cleos/main.cpp
Labels: bug

#849 Reset next primary keys on import genesis. #847
  libraries/chain/chaindb/cache_map.cpp
  libraries/chain/chaindb/controller.cpp
  libraries/chain/genesis/genesis_import.cpp
  libraries/chain/include/cyberway/chaindb/cache_map.hpp
  libraries/chain/include/cyberway/chaindb/controller.hpp
Labels: bug

#867 Add witnesses to EE-genesis #865
  programs/create-genesis/ee_genesis/event_engine_genesis.cpp
  programs/create-genesis/ee_genesis/event_engine_genesis.hpp
  programs/create-genesis/ee_genesis/genesis_ee_builder.cpp
  programs/create-genesis/ee_genesis/genesis_ee_builder.hpp
  programs/create-genesis/export_info.hpp
  programs/create-genesis/genesis_create.cpp
Labels: High
