Repository cyberway/cyberway, pull requests merged in 2019-05, with the labels that each got.

#600 Fix rewards in EE genesis #599
  programs/create-genesis-ee/genesis_ee_builder.cpp
  programs/create-genesis-ee/map_objects.hpp
Labels: bug

#602 Add common hash to reading dumped operations #601
  programs/create-genesis-ee/genesis_ee_builder.cpp
  programs/create-genesis-ee/genesis_ee_builder.hpp
  programs/create-genesis-ee/golos_dump_container.hpp
  programs/create-genesis-ee/golos_operations.hpp
Labels: bug

#606 Fix EOF check in operation dump reading #605
  programs/create-genesis-ee/genesis_ee_builder.cpp
Labels: bug

#618 Fix id-value for stake_stat #584
  programs/create-genesis/genesis_create.cpp
Labels: bug

#624 Genesis: votes for non-producers should be equal to -1
  programs/create-genesis/genesis_create.cpp
Labels: bug

#648 Remove obsolete assert
  libraries/chain/chaindb/cache_map.cpp
  libraries/chain/chaindb/controller.cpp
  libraries/chain/genesis/genesis_import.cpp
  libraries/chain/include/cyberway/chaindb/controller.hpp
  libraries/chain/include/cyberway/genesis/genesis_container.hpp
Labels: bug

#681 GenesisEndMessage #649
  libraries/chain/genesis/genesis_import.cpp
  plugins/event_engine_plugin/event_engine_plugin.cpp
  plugins/event_engine_plugin/include/eosio/event_engine_plugin/messages.hpp
Labels: High

#694 Fix overflow #691
  libraries/chain/chaindb/cache_map.cpp
  libraries/chain/eosio_contract_abi.cpp
  libraries/chain/include/cyberway/chaindb/cache_item.hpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/include/eosio/chain/resource_limits_private.hpp
  programs/create-genesis/genesis_create.cpp
Labels: bug

#723 Adopt API plugin for preparsed assets from chaindb. #707
  plugins/chain_api_plugin/chain_api_plugin.cpp
Labels: bug

#725 Fix reading uint128 rshares in genesis #703
  programs/create-genesis/genesis_create.cpp
  programs/create-genesis/golos_types.hpp
Labels: bug

#727 Fix operation_dump account_name_type bug #726
  programs/create-genesis/ee_genesis/genesis_ee_builder.cpp
Labels: High, bug

#735 Fix EE-genesis data end message #734
  plugins/event_engine_plugin/event_engine_plugin.cpp
  plugins/event_engine_plugin/include/eosio/event_engine_plugin/messages.hpp
Labels: High, bug

#740 Allow create EE-genesis without operation dump #739
  programs/create-genesis/ee_genesis/genesis_ee_builder.cpp
  programs/create-genesis/main.cpp
Labels: bug

#752 Tree for EE genesis messages to fix order #751
  programs/create-genesis/ee_genesis/genesis_ee_builder.cpp
  programs/create-genesis/ee_genesis/map_objects.hpp
Labels: High, bug

#756 Fix duplicate uniques on undo #755
  libraries/chain/chaindb/mongo_driver.cpp
  libraries/chain/include/cyberway/chaindb/journal.hpp
Labels: bug

#777 Add datastart message to EE-genesis #776
  plugins/event_engine_plugin/event_engine_plugin.cpp
Labels: High
